// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdtbwvyloaeixwxmvysj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdGJ3dnlsb2FlaXh3eG12eXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NjYxMjAsImV4cCI6MjA4ODA0MjEyMH0.2RG4Uhheky2fBI9iw7hmZuRbjhRuph5cRilyVp4Wbqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});